language: cpp
before_install:
# We need this line to have g++4.8 available in apt
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq gcc-4.8 g++-4.8 
# We want to compile with g++ 4.8 when rather than the default g++
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - wget https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz
  - sudo tar -C /usr/local -xzf go1.4.2.linux-amd64.tar.gz
  - sudo apt-get install python-numpy

language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
#install: 
# command to run tests, e.g. python setup.py test
script:  "python ./regtests/test-all.py"
